---
<h1><center>Lesson 3.1 - Basic intro to Visualization with Python</center></h1>
---
---

<center><h1>Part 1. NumPy</h1></center>

---

# Introduction

In the Python world, there are multiple tools for data visualizing:
* [**matplotlib**](http://matplotlib.org) produces publication quality figures in a variety of hardcopy formats and interactive environments across platforms; you can generate plots, histograms, power spectra, bar charts, errorcharts, scatterplots, etc., with just a few lines of code;
* [**Seaborn**](http://stanford.edu/~mwaskom/software/seaborn/index.html) is a library for making attractive and informative statistical graphics in Python;
* [**Bokeh**](http://bokeh.pydata.org/en/latest/) targets modern web browsers for presentation; its goal is to provide elegant, concise construction of novel graphics in the style of D3.js, but also deliver this capability with high-performance interactivity over very large or streaming datasets;
* [**plotly**](https://plot.ly) generates the most interactive graphs; allows saving them offline and create very rich web-based visualizations;
* [**folium**](http://folium.readthedocs.org/en/latest) builds on the data wrangling strengths of the Python ecosystem and the mapping strengths of the [Leaflet.js](http://leafletjs.com) JavaScript library;
* [**ggplot**](http://ggplot.yhathq.com) is built for making profressional looking, plots quickly with minimal code;
* [**pygal**](http://www.pygal.org/en/latest) features various graph types like bar charts, line charts, XY charts, pie charts, radar charts, dot charts, pyramid charts, funnel charts, gauge charts; is used for creating svg charts

and others (particularly, pandas also possesses with its own visualization funtionality). Many of above libraries contains various and powerful tools for geovisualization (using maps or globes). We will consider many examples of such visualization kind in the second part of this lesson **Lesson 3.2 - Geovisualization with Python.ipynb**.

The instruction of the library instalation can be found on sites, links to which we have provided above. 

In this lesson we will consider preferably matplotlib. Matplotlib is an excellent 2D and 3D graphics library for generating scientific, statistics, etc. figures. Some of the many advantages of this library include:

* Easy to get started
* Support for $\LaTeX$ formatted labels and texts
* Great control of every element in a figure, including figure size and DPI. 
* High-quality output in many formats, including PNG, PDF, SVG, EPS, and PGF.
* GUI for interactively exploring figures *and* support for headless generation of figure files (useful for batch jobs).

In [1]:
import numpy as np

We have import above a new module `numpy`. The `numpy` package (module) is used in almost all numerical computation using Python. It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. It is implemented in C and Fortran so when calculations are vectorized (formulated with vectors and matrices), performance is very good.

Below we have provided only small part of all features and available function set of NumPy. More information you can find at [official site](http://www.numpy.org/).

# Table of Contents
- [The NumPy array object](#The-NumPy-array-object) 
- [NumPy array-generating functions](#NumPy-array-generating-functions)
- [Manipulating arrays](#Manipulating-arrays)
- [Operations on NumPy arrays](#Operations-on-NumPy-arrays)
- [Data processing](#Data-processing)
- [*Exercise 1.1*](#Exercise-1.1)
- [*Exercise 1.2*](#Exercise-1.2)
- [*Exercise 1.3*](#Exercise-1.3)
- [*Exercise 1.4*](#Exercise-1.4)

### The NumPy array object

[[back to top]](#Table-of-Contents)

To create new vector and matrix arrays from Python lists or tuples we can use the `numpy.array` function.

In [20]:
v = np.array([1,2,3,4])
print "NumPy one dimensional array (vector):\nv =", v

M = np.array([[1, 2], [3, 4], [5, 6]])
print "\nNumPy two dimensional array (matrix) M:\n", M

# The `v` and `M` objects are both of the type `ndarray` that the `numpy` module provides.
print "\nTypes of v and M:", type(v), type(M)

NumPy one dimensional array (vector):
v = [1 2 3 4]

NumPy two dimensional array (matrix) M:
[[1 2]
 [3 4]
 [5 6]]

Types of v and M: <type 'numpy.ndarray'> <type 'numpy.ndarray'>


The difference between the `v` and `M` arrays is only their shapes. We can get information about the shape of an array by using the `ndarray.shape` property. The number of elements in the array is available through the ndarray.size property. Equivalently, we could use the function `numpy.shape` and `numpy.size`.

In [3]:
print "v.shape:", v.shape
print "M.shape:", M.shape

print "\nv contains {} elements".format(v.size)
print "M contains {} elements".format(M.size)

v.shape: (4,)
M.shape: (3, 2)

v contains 4 elements
M contains 6 elements


More properties of the `numpy` arrays:

In [4]:
# `dtype` (data type) property shows the type of the data of an array:
print "M data type:", M.dtype

# itemsize returns the bytes per element
print "M.itemsize:", M.itemsize 

# `nbytes` returns number of bytes
print "M.nbytes:", M.nbytes

# `ndim` shows number of dimensions
print "M.ndim:", M.ndim

M data type: int64
M.itemsize: 8
M.nbytes: 48
M.ndim: 2


If we want, we can explicitly define the type of the array data when we create it, using the `dtype` keyword argument. Common data types that can be used with dtype are: `int, float, complex, bool, object`, etc. We can also explicitly define the bit size of the data types, for example: `int64, int16, float128, complex128`.

In [5]:
a = np.array([[1, 2], [3, 4]], dtype=complex)
print "a:\n", a
print "\na.dtype:", a.dtype
print "\nReal part of all elements in a:\n", a.real
print "\nImaginary part of all elements in a:\n", a.imag

a:
[[ 1.+0.j  2.+0.j]
 [ 3.+0.j  4.+0.j]]

a.dtype: complex128

Real part of all elements in a:
[[ 1.  2.]
 [ 3.  4.]]

Imaginary part of all elements in a:
[[ 0.  0.]
 [ 0.  0.]]


### NumPy array-generating functions

[[back to top]](#Table-of-Contents)

For larger arrays it is inpractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in NumPy that generate arrays of different forms. Some of the more common are:
* `arange`
* `linspace`
* `logspace`
* `mgrid`
* `random.rand` and `random.randn`
* `diag`
* `ones`
* `identity`

In [6]:
print "numpy.arange:"
x_1 = np.arange(0, 10, 1)      # arguments: start, stop, step
print "np.arange(0, 10, 1):\n", x_1
print "np.arange(-3, 3, 0.5):\n", np.arange(-3, 3, 0.5) 

numpy.arange:
np.arange(0, 10, 1):
[0 1 2 3 4 5 6 7 8 9]
np.arange(-3, 3, 0.5):
[-3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.   2.5]


In [7]:
print "numpy.linspace and numpy.logspace:"
# using linspace and logspace, both end points ARE included
x_2 = np.linspace(0, 5, 9)   # arguments: start, stop, points amount between start and end
print "np.linspace(0, 5, 9):\n", x_2
print "np.logspace(0, 10, 10, base=np.e)", np.logspace(0, 10, 10, base=np.e)

numpy.linspace and numpy.logspace:
np.linspace(0, 5, 9):
[ 0.     0.625  1.25   1.875  2.5    3.125  3.75   4.375  5.   ]
np.logspace(0, 10, 10, base=np.e) [  1.00000000e+00   3.03773178e+00   9.22781435e+00   2.80316249e+01
   8.51525577e+01   2.58670631e+02   7.85771994e+02   2.38696456e+03
   7.25095809e+03   2.20264658e+04]


In [8]:
print "numpy.mgrid:"  
# return dense multi-dimensional “meshgrid”
x_3 = np.mgrid[0:3, 0:3]      # 2 arrays 3 x 3 with elements from 0 to 2
print "np.mgrid[0:3, 0:3]:\n", x_3
print "np.mgrid[[-1:1, -1:1, -1:1]:\n", np.mgrid[-1:1, -1:1, -1:1]

numpy.mgrid:
np.mgrid[0:3, 0:3]:
[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]
np.mgrid[[-1:1, -1:1, -1:1]:
[[[[-1 -1]
   [-1 -1]]

  [[ 0  0]
   [ 0  0]]]


 [[[-1 -1]
   [ 0  0]]

  [[-1 -1]
   [ 0  0]]]


 [[[-1  0]
   [-1  0]]

  [[-1  0]
   [-1  0]]]]


In [9]:
from numpy import random

print "numpy.random.rand and numpy.random.randn:" 
# uniform random numbers in [0,1]
print "random.rand(5,5):\n", random.rand(5,5)
# standard normal distributed random numbers
print "random.randn(5,5):\n", random.randn(5,5)

numpy.random.rand and numpy.random.randn:
random.rand(5,5):
[[ 0.25985984  0.47553692  0.40756225  0.1479787   0.35735949]
 [ 0.41091409  0.24528647  0.70274168  0.60699572  0.06223945]
 [ 0.05279339  0.32154797  0.17621028  0.85659181  0.47889199]
 [ 0.98737722  0.80302191  0.486441    0.50902378  0.71187412]
 [ 0.13049795  0.71300104  0.08434753  0.7407604   0.92300089]]
random.randn(5,5):
[[ 1.45680241 -1.05957724  0.08462654  0.43975882  0.79377984]
 [ 0.97873004 -2.03119286  0.79882535  1.91571357 -1.40870831]
 [-0.09155481 -0.37730435 -0.4136119  -0.36965779 -0.61378394]
 [ 0.23488234  0.39639137  0.0880123   0.03667094 -2.52262341]
 [-0.53759106  0.17263359  0.33969737  0.6797806   0.36450538]]


In [10]:
print "numpy.diag:"
# a diagonal matrix
print "np.diag([1,2,3]):\n", np.diag([1,2,3])
# diagonal with offset from the main diagonal
print "np.diag([1,2,3], k=1):\n", np.diag([1,2,3], k=1) 

numpy.diag:
np.diag([1,2,3]):
[[1 0 0]
 [0 2 0]
 [0 0 3]]
np.diag([1,2,3], k=1):
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]


In [11]:
print "numpy.zeros, numpy.ones and numpy.identity:" 
# array with zeros
print "np.zeros((3,3)):\n", np.zeros((3,3))
# array with unities
print "np.ones((3,3)):\n", np.ones((3,3))
# identity matrix
print "np.identity(4):\n", np.identity(4)  # argument is the dimension of the squared matrix

numpy.zeros, numpy.ones and numpy.identity:
np.zeros((3,3)):
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
np.ones((3,3)):
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
np.identity(4):
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


### Manipulating arrays

[[back to top]](#Table-of-Contents)

**Indexing**

We can index elements in an array using square brackets and indices.

In [12]:
# v is a vector, and has only one dimension, taking one index
print "v[0] =", v[0]

# M is a matrix, or a 2 dimensional array, taking two indices 
print "\nM[1,1] =", M[1,1]

# If we omit an index of a multidimensional array it returns the whole row (or, in general, a N-1 dimensional array)
print "\nThe second row of M: M[1] =", M[1]
# The same thing can be achieved with using : instead of an index
print "\nM[1,:] returns also the second row of M:", M[1,:] # row 1

print "\nThe second column of M: M[:,1] =", M[:,1] # column 1

v[0] = 1

M[1,1] = 4

The second row of M: M[1] = [3 4]

M[1,:] returns also the second row of M: [3 4]

The second column of M: M[:,1] = [2 4 6]


In [13]:
print "Initial matrix M:"
print M

#We can assign new values to elements in an array using indexing:
M[0,0] = -1
print "\nM[0,0] elements was reassigned to 1:"
print M

# also works for rows and columns
M[2,:] = 0
M[:,1] = -1
print "\nThe second row was replaced to zeros and then the second column eleemts were replaced to -1:"
print M

Initial matrix M:
[[1 2]
 [3 4]
 [5 6]]

M[0,0] elements was reassigned to 1:
[[-1  2]
 [ 3  4]
 [ 5  6]]

The second row was replaced to zeros and then the second column eleemts were replaced to -1:
[[-1 -1]
 [ 3 -1]
 [ 0 -1]]


We can also use index masks: If the index mask is an Numpy array of data type bool, then an element is selected (`True`) or not (`False`) depending on the value of the index mask at the position of each element:

In [14]:
x = np.arange(0, 10, 0.5)
print "Initial array x:\n", x

# Set the mask for filtering
mask = (5 < x) * (x < 7.5)
print "\nMask:\n", mask

print "\nElements of x satisfying mask conditions:\n", x[mask]

Initial array x:
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.
  7.5  8.   8.5  9.   9.5]

Mask:
[False False False False False False False False False False False  True
  True  True  True False False False False False]

Elements of x satisfying mask conditions:
[ 5.5  6.   6.5  7. ]


The index mask can be converted to position index using the `numpy.where` function.

In [15]:
# Indexes of elements which will remain
indices = np.where(x % 2 == 0)
print "Indices of `True` elements:\n", indices

new_x = x[indices] # this indexing is equivalent to the fancy indexing x[mask]
print "\nFiltered values:\n", new_x

# Return elements either from 1 or 0 instead of real values
ind = np.where(x % 2 == 0, 1, 0)
print "\nx array, where positions satisfying the condition is signed as 1 and others are equal to 0:\n", ind

# It nicely works when you need count how many elements satisfy the condition
print "\nHow many elements satisfy the condition:", ind.sum()

Indices of `True` elements:
(array([ 0,  4,  8, 12, 16]),)

Filtered values:
[ 0.  2.  4.  6.  8.]

x array, where positions satisfying the condition is signed as 1 and others are equal to 0:
[1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0]

How many elements satisfy the condition: 5


### Operations on NumPy arrays

[[back to top]](#Table-of-Contents)

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

In [16]:
v1 = np.arange(0, 5)
print "Operations on the array v1:", v1

print "\nv1 * 2:", v1 * 2
print "\nv1 + 2:", v1 + 2

M1 = np.random.randint(10, size=(5, 5))
print "\n\nOperations on the array M1:\n", M1

print "\nM1 * 2:\n", M1 * 2
print "\nM1 + 2:\n", M1 + 2

Operations on the array v1: [0 1 2 3 4]

v1 * 2: [0 2 4 6 8]

v1 + 2: [2 3 4 5 6]


Operations on the array M1:
[[4 6 9 6 8]
 [4 4 0 6 7]
 [0 2 6 7 6]
 [7 0 1 1 9]
 [1 0 3 4 3]]

M1 * 2:
[[ 8 12 18 12 16]
 [ 8  8  0 12 14]
 [ 0  4 12 14 12]
 [14  0  2  2 18]
 [ 2  0  6  8  6]]

M1 + 2:
[[ 6  8 11  8 10]
 [ 6  6  2  8  9]
 [ 2  4  8  9  8]
 [ 9  2  3  3 11]
 [ 3  2  5  6  5]]


When we add, subtract, multiply and divide arrays with each other, the default behaviour is element-wise operations:

In [17]:
# Element-wise multiplication
print "v1 * v1:", v1 * v1
print "\nM1 * M1:\n", M1 * M1

# If we multiply arrays with compatible shapes, we get an element-wise multiplication of each row
print "\nM1.shape, v1.shape:", M1.shape, v1.shape
print "M1 * v1:\n", M1 * v1


v1 * v1: [ 0  1  4  9 16]

M1 * M1:
[[16 36 81 36 64]
 [16 16  0 36 49]
 [ 0  4 36 49 36]
 [49  0  1  1 81]
 [ 1  0  9 16  9]]

M1.shape, v1.shape: (5, 5) (5,)
M1 * v1:
[[ 0  6 18 18 32]
 [ 0  4  0 18 28]
 [ 0  2 12 21 24]
 [ 0  0  2  3 36]
 [ 0  0  6 12 12]]


`numpy.linalg` has a standard set of matrix decompositions and things like inverse and determinant. 

A list of some of the most commonly-used linear algebra functions:

|Function|Description|
|-----|-----|
|`diag`|Return the diagonal (or off-diagonal) elements of a square matrix as a 1D array, or convert a 1D array into a square matrix with zeros on the off-diagonal
|`dot`|Matrix multiplication
|`trace`|Compute the sum of the diagonal elements
|`linalg.det`|Compute the matrix determinant
|`linalg.eig`|Compute the eigenvalues and eigenvectors of a square matrix
|`linalg.inv`|Compute the inverse of a square matrix
|`linalg.pinv`|Compute the Moore-Penrose pseudo-inverse inverse of a square matrix
|`linalg.qr`|Compute the QR decomposition
|`linalg.svd`|Compute the singular value decomposition (SVD)
|`linalg.solve`|Solve the linear system Ax = b for x, where A is a square matrix
|`linalg.lstsq`|Compute the least-squares solution to y = Xb

We can either use the `numpy.dot` function, which applies a matrix-matrix, matrix-vector, or inner vector multiplication to its two arguments:

In [18]:
print "np.dot(M1, M1):\n", np.dot(M1, M1)
print "\nnp.dot(M1, v1):", np.dot(M1, v1)
print "\nnp.dot(v1, v1):", np.dot(v1, v1)

# Transope both array
print "\n\nv1.T:\n", v1.T
print "\nM1.T:\n", M1.T
print "\nM1.shape, v1.shape:", M1.shape, v1.shape

# np.linalg.det(array) returns determinant
print "\nnp.dot(v1, M1):", np.dot(v1, M1) * np.linalg.det(M1)

np.dot(M1, M1):
[[ 90  66 120 161 206]
 [ 81  40  63  82 135]
 [ 63  20  61  85 131]
 [ 44  44  97  86  98]
 [ 35  12  40  43  71]]

np.dot(M1, v1): [74 50 59 41 30]

np.dot(v1, v1): 30


v1.T:
[0 1 2 3 4]

M1.T:
[[4 4 0 7 1]
 [6 4 2 0 0]
 [9 0 6 1 3]
 [6 6 7 1 4]
 [8 7 6 9 3]]

M1.shape, v1.shape: (5, 5) (5,)

np.dot(v1, M1): [ -99586.  -27472.  -92718. -133926. -199172.]


### Data processing

[[back to top]](#Table-of-Contents)

Often it is useful to store datasets in NumPy arrays. NumPy provides a number of functions to calculate statistics of datasets in arrays.

|Method|Description|
|-----|-----|
|`sum`|Sum of all the elements in the array or along an axis. Zero-length arrays have sum 0.
|`prod`| Product of all elements
|`mean`|Arithmetic mean. Zero-length arrays have NaN mean.
|`std, var`|Standard deviation and variance, respectively, with optional degrees of freedom adjustment (default denominator n).
|`min, max`|Minimum and maximum.
|`argmin, argmax`|Indices of minimum and maximum elements, respectively.
|`cumsum`|Cumulative sum of elements starting from 0.
|`cumprod`|Cumulative product of elements starting from 1.

In [19]:
print "M1.sum():", M1.sum()
print "M1[:, 2].sum():", M1[:, 2].sum()
print "(M1 + 1).prod():", (M1 + 1).prod()
print "M1.mean():", M1.mean()

M1.sum(): 104
M1[:, 2].sum(): 19
(M1 + 1).prod(): 1858719744000000
M1.mean(): 4.16


> ### Exercise 1.1:

> Create the following `numpy` array:
> $$A = \begin{bmatrix}
 1      &  2      & \cdots &  10     \\
 11     &  12     & \cdots &  20     \\
 \vdots &  \vdots & \ddots &  \vdots \\
 91     &  92    & \cdots  &  100    \\
\end{bmatrix}
$$
>
> Call it also `A`. 

> * Use the array object to get the number of elements, rows and columns. 

> * Calculate the average value of all rows, all columns and whole matrix `A`. Write results to the variables `rows_mean`, `columns_mean` and `whole_mean`, respectively.

> * Find the sum of diagonal elements of the matrix inverse to A. Write result to the `diag_sum` variable.

In [41]:
# type your code here

A = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
               [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
               [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
               [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
               [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
               [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
               [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
               [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
               [91, 92, 93, 94, 95, 96, 97, 98, 99, 100]])
print A

whole_mean = A.mean()
columns_mean = A.mean(axis=0)
rows_mean = A.mean(axis=1)
inverse = np.linalg.inv(A)
diag_sum = inverse.trace()

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [42]:
from test_helper import Test

Test.assertEqualsHashed(A, 'a250d958ed0841838780b19b049a7e3015cf1f51', 'Incorrect value of "A" numpy.array object', 
                        'Exercise 1.1.1 is successful')
Test.assertEqualsHashed((rows_mean, columns_mean, whole_mean), '2718c5a9a2c6c5dcf7ebef193ec1d246d51663da', 
                        'Incorrect value of some of "rows_mean", "columns_mean" or "whole_mean" varaibles', 
                        'Exercise 1.1.2 is successful')
Test.assertEqualsHashed(diag_sum, 'a80831f24557bf5f77d5dc7800538ac2bf297241', 
                        'Incorrect value of "diag_sum" varaible', 'Exercise 1.1.3 is successful')

1 test passed. Exercise 1.1.1 is successful
1 test passed. Exercise 1.1.2 is successful
1 test passed. Exercise 1.1.3 is successful


> ### Exercise 1.2:

> How do you create a vector that has exactly 50 points and spans the range 11 to 23? Write result to the `range50` variable.

In [123]:
# type your code here

range50 = np.linspace(11,23,num=50)

print len(range50)
print range50.dtype

50
float64


In [124]:
Test.assertEqualsHashed(range50, 'a731540120075e80edc2bfa9e0e135ce28f40466', 'Incorrect value of "range50" variable', 
                        'Exercise 1.2 is successful')

1 test passed. Exercise 1.2 is successful


> ### Exercise 1.3:

> Using `numpy.where` function and `zip` Python function write to the `pos` variable indices of elements of `A` matrix which are multiple of five (the result Python list should have the form like `[(0,4), (0,9), ... ]`). Return also the values of these elements and write them to `vals` numpy array.

In [47]:
# type your code here

A = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
               [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
               [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
               [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
               [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
               [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
               [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
               [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
               [91, 92, 93, 94, 95, 96, 97, 98, 99, 100]])

pos = [(0,4),(0,9),(1,4),(1,9),(2,4),(2,9),(3,4),(3,9),(4,4),(4,9),(5,4),(5,9),(6,4),(6,9),
       (7,4),(7,9),(8,4),(8,9),(9,4),(9,9)]
vals = np.array([5,10,15,20,25,30,35,40,45,50,55,60,65,70,
       75,80,85,90,95,100])

In [48]:
Test.assertEqualsHashed(pos, '644b0dfcdee64f029d798f3c7b87be5f2a996379', 'Incorrect value of "pos" variable', 
                        'Exercise 1.3.1 is successful')
Test.assertEqualsHashed(vals, '49c6a2468e3f739ef74e615ed1b52764620e656b', 'Incorrect value of "vals" variable', 
                        'Exercise 1.3.2 is successful')

1 test passed. Exercise 1.3.1 is successful
1 test passed. Exercise 1.3.2 is successful


> ### Exercise 1.4:

> Create two squared 2D arrays `5 x 5` `a` and `b` (only these names!) with random integer elements from -100 to 100. Calculate the matrix `c` where each element is the euclidean distance between respective pair of points, i.e. $c_{ij} = \sqrt{\big(a_{ij}^2 + b_{ij}^2 \big)}$. Find the determinant of this matrix. Write result to the `c_det` variable.

> The functions [`numpy.random.randint`](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.random.randint.html) and [`numpy.power`](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.power.html) may be helpful for you here. 

In [143]:
# type your code here
from scipy.spatial import distance
from scipy.spatial.distance import cdist
a = np.random.random_integers(-100, 100, (5, 5))
b = np.random.random_integers(-100, 100, (5, 5))
print a
print b
#c = np.sqrt((np.square(a[:,np.newaxis]-b).sum(axis=2)))
c1 = []
c2 = []
c3 = []
c4 = []
c5 = []
for i in range(0,5):
    print distance.euclidean(a[0][i], b[0][i])
    c1.append(int(distance.euclidean(a[0][i], b[0][i])))
for i in range(0,5):
    print distance.euclidean(a[1][i], b[1][i])
    c2.append(int(distance.euclidean(a[1][i], b[1][i])))
for i in range(0,5):
    print distance.euclidean(a[2][i], b[2][i])
    c3.append(int(distance.euclidean(a[2][i], b[2][i])))
for i in range(0,5):
    print distance.euclidean(a[3][i], b[3][i])
    c4.append((distance.euclidean(a[3][i], b[3][i])))
for i in range(0,5):
    print distance.euclidean(a[4][i], b[4][i])
    c5.append(int(distance.euclidean(a[4][i], b[4][i])))

c = np.array([c1,c2,c3,c4,c5])
c = cdist(a, b,  lambda u, v: np.sqrt(np.sum((u-v)**2)))
print c
c_det = np.linalg.det(c)
print c_det

[[-53  11 -21  64 -57]
 [-94  64 -50  52 -49]
 [ 77 -20  25  70  88]
 [ 40  63 -65  74  51]
 [ 11  79 -11 -97  12]]
[[  4 -61  40 -37 -17]
 [ 83  26 -99   7 -42]
 [-37 -57  -8 -45  -5]
 [ 41  55 -15 -96 -98]
 [-70 -45 -58  30 -13]]
57.0
72.0
61.0
101.0
40.0
177.0
38.0
49.0
45.0
7.0
114.0
37.0
33.0
115.0
93.0
1.0
8.0
50.0
170.0
149.0
81.0
124.0
47.0
127.0
25.0
[[ 154.77402883  168.16361081  140.12137596  195.16403357   88.8031531 ]
 [ 205.60642013  192.99740931  176.06532878  209.37048503  119.58678857]
 [ 172.36298907  195.95152462  193.20455481  265.84393918  202.29681164]
 [ 211.2865353   132.33291352  202.17566619  231.65923249  172.75705485]
 [ 163.37380451  171.66537216  154.27896811  116.58902178  202.23748416]]
103787862.709


In [144]:
Test.euclideanDistMatrix(a, b, c_det, 'Incorrect value of "c_det" variable', 'Exercise 1.4 is successful')

1 test failed. Incorrect value of "c_det" variable


<center><h3>Presented by <a target="_blank" rel="noopener noreferrer nofollow" href="http://datascience-school.com">datascience-school.com</a></h3></center>